// criando teste da rota

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Davi",
    "email": "davi@example.com",
    "password": "123456"
}

###

GET http://localhost:3333/users/1
Content-Type: application/json


###

PUT http://localhost:3333/users/4
Content-Type: application/json

{
    "fullName": "Marcela",
    "email": "marcelo@e.com",
    "password": "marcelopassword"
}

###

DELETE http://localhost:3333/users/4